
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/Visual Studio Comunity/Comunity/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/Visual Studio Comunity/Comunity/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Visual Studio Comunity/Comunity/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Visual Studio Comunity/Comunity/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versión de MSBuild 17.9.8+b34f75857 para .NET Framework
      Compilación iniciada a las 31/1/2025 07:15:05.
      
      Proyecto "E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\3.28.0-msvc1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        La salida estructurada está habilitada. El formato del diagnóstico del compilador reflejará la jerarquía de errores. Consulte https://aka.ms/cpp/structured-output para obtener más detalles.
        Creando directorio "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Se creará "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        E:\\Visual Studio Comunity\\Comunity\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        E:\\Visual Studio Comunity\\Comunity\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\3.28.0-msvc1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=E:\\Visual Studio Comunity\\Comunity\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminará el archivo "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Compilación del proyecto terminada "E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\3.28.0-msvc1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinos predeterminados).
      
      Compilación correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:03.45
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/flutter-learning/projects/sentences_tester/build/windows/x64/CMakeFiles/3.28.0-msvc1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/Visual Studio Comunity/Comunity/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/Visual Studio Comunity/Comunity/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/flutter-learning/projects/sentences_tester/build/windows/x64/CMakeFiles/CMakeScratch/TryCompile-lpjehs"
      binary: "E:/flutter-learning/projects/sentences_tester/build/windows/x64/CMakeFiles/CMakeScratch/TryCompile-lpjehs"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/flutter-learning/projects/sentences_tester/build/windows/x64/CMakeFiles/CMakeScratch/TryCompile-lpjehs'
        
        Run Build Command(s): "E:/Visual Studio Comunity/Comunity/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_21aaa.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versión de MSBuild 17.9.8+b34f75857 para .NET Framework
        Compilación iniciada a las 31/1/2025 07:15:09.
        
        Proyecto "E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\CMakeScratch\\TryCompile-lpjehs\\cmTC_21aaa.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_21aaa.dir\\Debug\\".
          La salida estructurada está habilitada. El formato del diagnóstico del compilador reflejará la jerarquía de errores. Consulte https://aka.ms/cpp/structured-output para obtener más detalles.
          Creando directorio "E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\CMakeScratch\\TryCompile-lpjehs\\Debug\\".
          Creando directorio "cmTC_21aaa.dir\\Debug\\cmTC_21aaa.tlog\\".
        InitializeBuildStatus:
          Se creará "cmTC_21aaa.dir\\Debug\\cmTC_21aaa.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_21aaa.dir\\Debug\\cmTC_21aaa.tlog\\unsuccessfulbuild".
        ClCompile:
          E:\\Visual Studio Comunity\\Comunity\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_21aaa.dir\\Debug\\\\" /Fd"cmTC_21aaa.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "E:\\Visual Studio Comunity\\Comunity\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilador de optimización de C/C++ de Microsoft (R) versión 19.39.33523 para x64
          (C) Microsoft Corporation. Todos los derechos reservados.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_21aaa.dir\\Debug\\\\" /Fd"cmTC_21aaa.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "E:\\Visual Studio Comunity\\Comunity\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          E:\\Visual Studio Comunity\\Comunity\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\CMakeScratch\\TryCompile-lpjehs\\Debug\\cmTC_21aaa.exe" /INCREMENTAL /ILK:"cmTC_21aaa.dir\\Debug\\cmTC_21aaa.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/flutter-learning/projects/sentences_tester/build/windows/x64/CMakeFiles/CMakeScratch/TryCompile-lpjehs/Debug/cmTC_21aaa.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/flutter-learning/projects/sentences_tester/build/windows/x64/CMakeFiles/CMakeScratch/TryCompile-lpjehs/Debug/cmTC_21aaa.lib" /MACHINE:X64  /machine:x64 cmTC_21aaa.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_21aaa.vcxproj -> E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\CMakeScratch\\TryCompile-lpjehs\\Debug\\cmTC_21aaa.exe
        FinalizeBuildStatus:
          Se eliminará el archivo "cmTC_21aaa.dir\\Debug\\cmTC_21aaa.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_21aaa.dir\\Debug\\cmTC_21aaa.tlog\\cmTC_21aaa.lastbuildstate".
        Compilación del proyecto terminada "E:\\flutter-learning\\projects\\sentences_tester\\build\\windows\\x64\\CMakeFiles\\CMakeScratch\\TryCompile-lpjehs\\cmTC_21aaa.vcxproj" (destinos predeterminados).
        
        Compilación correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:01.23
        
      exitCode: 0
...
